name: Checkmarx One Scan
on:
  push:
    branches:
      - master
      - feature/187
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: SHNodeGoat
          cx_tenant: cxone-samh
          base_uri: https://ast.checkmarx.net
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
      - name: Run DAST Scan
        uses: checkmarx/dast-github-action@v1.0
        env:
            CX_APIKEY: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJjZDBmN2QxMS00YjE0LTQ3YTUtYTlhMy1lMmI2M2YwOTUwZTAifQ.eyJpYXQiOjE2ODcyOTI2NDcsImp0aSI6IjQ5N2M5NWMxLTM5NjktNGFhOS04ZWMyLTZlMDEyNzk4NmE4ZSIsImlzcyI6Imh0dHBzOi8vaWFtLmNoZWNrbWFyeC5uZXQvYXV0aC9yZWFsbXMvY3hvbmUtc2FtaCIsImF1ZCI6Imh0dHBzOi8vaWFtLmNoZWNrbWFyeC5uZXQvYXV0aC9yZWFsbXMvY3hvbmUtc2FtaCIsInN1YiI6IjhjODRkNTgzLTgyNTAtNGJlYi04MGViLWY5YzE1N2QxYzU0MSIsInR5cCI6Ik9mZmxpbmUiLCJhenAiOiJhc3QtYXBwIiwic2Vzc2lvbl9zdGF0ZSI6IjAxMjIwMTE3LTY4MDAtNDY5ZS05MmRiLWI1MDI2YTZjZDhmOCIsInNjb3BlIjoiIG9mZmxpbmVfYWNjZXNzIiwic2lkIjoiMDEyMjAxMTctNjgwMC00NjllLTkyZGItYjUwMjZhNmNkOGY4In0.Z5kO33Y3_GWIlQFqm68dk9QXj9JGAN-A4zIUChZcxRs
        with:
          command: "web"
          config: 'testphp.yaml'
          base_url: "http://testasp.vulnweb.com"
          environment_id: "ed00d705-19f6-4a1a-9514-b34c989af554"
          fail_on: "HIGH"
          verbose: true            
